# docker-compose.production.yml

volumes:
  pg_data_production:
  static_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    image: mortimers/taski_backend # Качаем с Docker Hub
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static_volume:/backend_static
  frontend:
    image: mortimers/taski_frontend  # Качаем с Docker Hub
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: mortimers/taski_gateway  # Качаем с Docker Hub
    depends_on:
      - backend
    volumes:
      - static_volume:/staticfiles/
    ports:
      - "127.0.0.1:9000:80"
